name: httkweb

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout httk-web
      uses: actions/checkout@v4
      with:
        path: web
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        cd web
        pip install .
        cd ..
    - name: Generate website
      run: |
        cd web
        python3 ./publish_static.py
        cd ..
    - name: Publish website
      run: |
        cd web
        git config user.name httkweb-github-action
        git config user.email '<>'
        git fetch origin gh-pages
        git checkout gh-pages
        mv docs ../gh-pages
        mv .git ../gh-pages
        cd ../gh-pages
        touch .nojekyll
        git add .
        git commit -m "Generated website contents $(date --rfc-2822)"
        git push
